#!/bin/bash

# Author: Marcelo Vázquez (aka S4vitar)

#Colours
declare -r greenColour="\e[0;32m\033[1m"
declare -r endColour="\033[0m\e[0m"
declare -r redColour="\e[0;31m\033[1m"
declare -r blueColour="\e[0;34m\033[1m"
declare -r yellowColour="\e[0;33m\033[1m"
declare -r purpleColour="\e[0;35m\033[1m"
declare -r turquoiseColour="\e[0;36m\033[1m"
declare -r grayColour="\e[0;37m\033[1m"

# Global Variables
declare -r USER_AGENT="User-Agent: htbExplorer"
declare -r url_machines_get_all="https://hackthebox.eu/api/machines/get/all"
declare -r url_global_data="https://www.hackthebox.eu/api/stats/global"
declare -r url_user_id="https://www.hackthebox.eu/api/user/id"
declare -r tmp_file="tmp.json"

trap ctrl_c INT

function ctrl_c(){
    tput cnorm
    echo -e "\n\n${redColour}[!] Exiting...${endColour}"
    rm getAllMachines 2>/dev/null
    exit 1
}

function printTable(){

    local -r delimiter="${1}"
    local -r data="$(removeEmptyLines "${2}")"

    if [[ "${delimiter}" != '' && "$(isEmptyString "${data}")" = 'false' ]]
    then
        local -r numberOfLines="$(wc -l <<< "${data}")"

        if [[ "${numberOfLines}" -gt '0' ]]
        then
            local table=''
            local i=1

            for ((i = 1; i <= "${numberOfLines}"; i = i + 1))
            do
                local line=''
                line="$(sed "${i}q;d" <<< "${data}")"

                local numberOfColumns='0'
                numberOfColumns="$(awk -F "${delimiter}" '{print NF}' <<< "${line}")"

                if [[ "${i}" -eq '1' ]]
                then
                    table="${table}$(printf '%s#+' "$(repeatString '#+' "${numberOfColumns}")")"
                fi

                table="${table}\n"

                local j=1

                for ((j = 1; j <= "${numberOfColumns}"; j = j + 1))
                do
                    table="${table}$(printf '#| %s' "$(cut -d "${delimiter}" -f "${j}" <<< "${line}")")"
                done

                table="${table}#|\n"

                if [[ "${i}" -eq '1' ]] || [[ "${numberOfLines}" -gt '1' && "${i}" -eq "${numberOfLines}" ]]
                then
                    table="${table}$(printf '%s#+' "$(repeatString '#+' "${numberOfColumns}")")"
                fi
            done

            if [[ "$(isEmptyString "${table}")" = 'false' ]]
            then
                echo -e "${table}" | column -s '#' -t | awk '/^\+/{gsub(" ", "-", $0)}1'
            fi
        fi
    fi
}

function removeEmptyLines(){

    local -r content="${1}"
    echo -e "${content}" | sed '/^\s*$/d'
}

function repeatString(){

    local -r string="${1}"
    local -r numberToRepeat="${2}"

    if [[ "${string}" != '' && "${numberToRepeat}" =~ ^[1-9][0-9]*$ ]]
    then
        local -r result="$(printf "%${numberToRepeat}s")"
        echo -e "${result// /${string}}"
    fi
}

function isEmptyString(){

    local -r string="${1}"

    if [[ "$(trimString "${string}")" = '' ]]
    then
        echo 'true' && return 0
    fi

    echo 'false' && return 1
}

function trimString(){

    local -r string="${1}"
    sed 's,^[[:blank:]]*,,' <<< "${string}" | sed 's,[[:blank:]]*$,,'
}

function generateFiles(){

    echo '' > $tmp_file

    while [ "$(cat $tmp_file | wc -l)" != "0" ]; do
        curl -s -H "$USER_AGENT" "$url_machines_get_all?api_token=$API_TOKEN" -X GET -L | tr "'" '"' | sed 's/None/\"None\"/g' | sed 's/True/\"True\"/g' | sed 's/False/\"False\"/g' > $tmp_file
    done
}

function getGlobalData(){

    echo "Sessions, Active VPNs, Total Machines" > global_data
    curl -s -X POST $url_global_data | tr "'" '"' | jq '.["data"]["sessions","vpn","machines"]' | xargs | tr ' ' ',' >> global_data
    echo -ne "${grayColour}"
    printTable ',' "$(cat global_data)"
    echo -ne "${endColour}"
    rm global_data 2>/dev/null
}

function getAllMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getAllMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do

        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getAllMachines
        let id+=1
    done

    echo -ne "${greenColour}"
    printTable ',' "$(cat getAllMachines)"
    echo -e "${endColour}"
    rm getAllMachines 2>/dev/null
}

function getActiveMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getActiveMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getActiveMachines
        let id+=1
    done

    sed -i '/Is Active/!d' getActiveMachines
    sed -i '1 i\Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab' getActiveMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getActiveMachines)"
    echo -e "${endColour}"
    rm getActiveMachines 2>/dev/null
}

function getRetiredMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getRetiredMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getRetiredMachines
        let id+=1
    done

    sed -i '/Is Active/d' getRetiredMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getRetiredMachines)"
    echo -e "${endColour}"
    rm getRetiredMachines 2>/dev/null
}

function getActiveLinuxMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getActiveLinuxMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getActiveLinuxMachines
        let id+=1
    done

    sed -i '/Is Active/!d' getActiveLinuxMachines
	sed -i '/Windows/d' getActiveLinuxMachines
    sed -i '/Other/d' getActiveLinuxMachines
    sed -i '/Solaris/d' getActiveLinuxMachines
    sed -i '/OpenBSD/d' getActiveLinuxMachines
    sed -i '/FreeBSD/d' getActiveLinuxMachines
    sed -i '1 i\Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab' getActiveLinuxMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getActiveLinuxMachines)"
    echo -e "${endColour}"
    rm getActiveLinuxMachines 2>/dev/null
}

function getActiveWindowsMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getActiveWindowsMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getActiveWindowsMachines
        let id+=1
    done

    sed -i '/Is Active/!d' getActiveWindowsMachines
	sed -i '/Linux/d' getActiveWindowsMachines
	sed -i '/FreeBSD/d' getActiveWindowsMachines
    sed -i '/OpenBSD/d' getActiveWindowsMachines
    sed -i '/Other/d' getActiveWindowsMachines
    sed -i '/Solaris/d' getActiveWindowsMachines
    sed -i '1 i\Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab' getActiveWindowsMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getActiveWindowsMachines)"
    echo -e "${endColour}"
    rm getActiveWindowsMachines 2>/dev/null
}

function getActiveFreebsdMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getActiveFreebsdMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getActiveFreebsdMachines
        let id+=1
    done

    sed -i '/Is Active/!d' getActiveFreebsdMachines
	sed -i '/Linux/d' getActiveFreebsdMachines
    sed -i '/Windows/d' getActiveFreebsdMachines
    sed -i '/OpenBSD/d' getActiveFreebsdMachines
    sed -i '/Other/d' getActiveFreebsdMachines
    sed -i '/Solaris/d' getActiveFreebsdMachines
    sed -i '1 i\Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab' getActiveFreebsdMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getActiveFreebsdMachines)"
    echo -e "${endColour}"
    rm getActiveFreebsdMachines 2>/dev/null
}

function getActiveOpenbsdMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getActiveOpenbsdMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getActiveOpenbsdMachines
        let id+=1
    done

    sed -i '/Is Active/!d' getActiveOpenbsdMachines
	sed -i '/Linux/d' getActiveOpenbsdMachines
    sed -i '/Windows/d' getActiveOpenbsdMachines
    sed -i '/FreeBSD/d' getActiveOpenbsdMachines
    sed -i '/Other/d' getActiveOpenbsdMachines
    sed -i '/Solaris/d' getActiveOpenbsdMachines
    sed -i '1 i\Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab' getActiveOpenbsdMachines
    
    echo -ne "${greenColour}"
    printTable ',' "$(cat getActiveOpenbsdMachines)"
    echo -e "${endColour}"
    rm getActiveOpenbsdMachines 2>/dev/null
}

function getActiveOtherMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getActiveOtherMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getActiveOtherMachines
        let id+=1
    done

    sed -i '/Is Active/!d' getActiveOtherMachines
	sed -i '/Linux/d' getActiveOtherMachines
    sed -i '/Windows/d' getActiveOtherMachines
    sed -i '/FreeBSD/d' getActiveOtherMachines
    sed -i '/OpenBSD/d' getActiveOtherMachines
    sed -i '/Solaris/d' getActiveOtherMachines
    sed -i '1 i\Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab' getActiveOtherMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getActiveOtherMachines)"
    echo -e "${endColour}"
    rm getActiveOtherMachines 2>/dev/null
}

function getRetiredWindowsMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getRetiredWindowsMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getRetiredWindowsMachines
        let id+=1
    done

    sed -i '/Is Active/d' getRetiredWindowsMachines
	sed -i '/Linux/d' getRetiredWindowsMachines
	sed -i '/FreeBSD/d' getRetiredWindowsMachines
    sed -i '/OpenBSD/d' getRetiredWindowsMachines
    sed -i '/Other/d' getRetiredWindowsMachines
    sed -i '/Solaris/d' getRetiredWindowsMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getRetiredWindowsMachines)"
    echo -e "${endColour}"
    rm getRetiredWindowsMachines 2>/dev/null
}

function getRetiredFreebsdMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getRetiredFreebsdMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getRetiredFreebsdMachines
        let id+=1
    done

    sed -i '/Is Active/d' getRetiredFreebsdMachines
	sed -i '/Linux/d' getRetiredFreebsdMachines
    sed -i '/Windows/d' getRetiredFreebsdMachines
    sed -i '/OpenBSD/d' getRetiredFreebsdMachines
    sed -i '/Other/d' getRetiredFreebsdMachines
    sed -i '/Solaris/d' getRetiredFreebsdMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getRetiredFreebsdMachines)"
    echo -e "${endColour}"
    rm getRetiredFreebsdMachines 2>/dev/null
}

function getRetiredOpenbsdMachines(){
 
    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getRetiredOpenbsdMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getRetiredOpenbsdMachines
        let id+=1
    done

    sed -i '/Is Active/d' getRetiredOpenbsdMachines
	sed -i '/Linux/d' getRetiredOpenbsdMachines
    sed -i '/Windows/d' getRetiredOpenbsdMachines
    sed -i '/FreeBSD/d' getRetiredOpenbsdMachines
    sed -i '/Other/d' getRetiredOpenbsdMachines
    sed -i '/Solaris/d' getRetiredOpenbsdMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getRetiredOpenbsdMachines)"
    echo -e "${endColour}"
    rm getRetiredOpenbsdMachines 2>/dev/null
}

function getRetiredLinuxMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getRetiredLinuxMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getRetiredLinuxMachines
        let id+=1
    done

    sed -i '/Is Active/d' getRetiredLinuxMachines
	sed -i '/Windows/d' getRetiredLinuxMachines
	sed -i '/FreeBSD/d' getRetiredLinuxMachines
    sed -i '/OpenBSD/d' getRetiredLinuxMachines
    sed -i '/Other/d' getRetiredLinuxMachines
    sed -i '/Solaris/d' getRetiredLinuxMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getRetiredLinuxMachines)"
    echo -ne "${endColour}"
    rm getRetiredLinuxMachines 2>/dev/null
}

function getRetiredOtherMachines(){

    getGlobalData
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> getRetiredOtherMachines

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')                                                                                                                                                                        
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> getRetiredOtherMachines
        let id+=1
    done

    sed -i '/Is Active/d' getRetiredOtherMachines
	sed -i '/Windows/d' getRetiredOtherMachines
    sed -i '/Linux/d' getRetiredOtherMachines
	sed -i '/FreeBSD/d' getRetiredOtherMachines
    sed -i '/OpenBSD/d' getRetiredOtherMachines
    sed -i '/Solaris/d' getRetiredOtherMachines

    echo -ne "${greenColour}"
    printTable ',' "$(cat getRetiredOtherMachines)"
    echo -e "${endColour}"
    rm getRetiredOtherMachines 2>/dev/null
}

function searchMachineName(){

    getGlobalData
	s_machine_name=$1
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> searchMachineName

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> searchMachineName
        let id+=1
    done

	sed -i "/$s_machine_name/!d" searchMachineName
	sed -i '1 i\Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab' searchMachineName

    printTable ',' "$(cat searchMachineName)"
    tput cnorm; rm searchMachineName 2>/dev/null
}

function searchIPAddress(){

    getGlobalData
    ipAddress=$1
    echo "Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab" >> searchIPAddress

    id=0; while [ "$field_value" != "null,null,null,null,null,null,null,null,null,null,null" ]; do
        field_value=$(cat $tmp_file | jq ".[$id][\"name\",\"ip\",\"os\",\"points\",\"rating\",\"user_owns\",\"root_owns\",\"retired\",\"release\",\"retired_date\",\"free\"]" | tr -d '"' | xargs | tr ' ' ',')
        if [ "$(echo $field_value)" == "null,null,null,null,null,null,null,null,null,null,null" ]; then
            break
        fi

        echo $field_value | sed 's/true/Yes/g' | sed 's/false/No/g' | sed 's/null/Is Active/' >> searchIPAddress
        let id+=1
    done

	sed -i "/$ipAddress,/!d" searchIPAddress
	sed -i '1 i\Name, IP Address, Operating System, Points, Rating, User Owns, Root Owns, Retired, Release Date, Retired Date, Free Lab' searchIPAddress

    printTable ',' "$(cat searchIPAddress)"
    tput cnorm; rm searchIPAddress 2>/dev/null
}

function searchUserName(){

    username=$1
    id_username=$(curl -s -X POST "$url_user_id?api_token=$API_TOKEN" -L --data "username=$username" | tr "'" '"' | sed 's/None/\"None\"/g' | sed 's/True/\"True\"/g' | sed 's/False/\"False\"/g' | jq '.["id"]')

    if [ $id_username ]; then
        echo "Username,ID,HTB Profile" > searchUserName
        echo "$username,$id_username,https://www.hackthebox.eu/home/users/profile/$id_username" >> searchUserName

        echo -ne "${yellowColour}"
        printTable ',' "$(cat searchUserName)"
        echo -ne "${endColour}"
        tput cnorm; rm searchUserName 2>/dev/null
    fi
}

function helpPanel(){
    echo -e "\n${redColour}[!] Usage: ./htbExplorer${endColour}\n"
    echo -e "\t${grayColour}[-t]${endColour}${yellowColour} API Token${endColour} ${redColour}[Required]${endColour}\n"
    echo -e "\t${grayColour}[-g]${endColour}${yellowColour} Generate Files${endColour} ${redColour}[Required]${endColour}"
    echo -e "\t\t${purpleColour}0${endColour}${yellowColour}: No${endColour}"
    echo -e "\t\t${purpleColour}1${endColour}${yellowColour}: Yes${endColour}\n"
    echo -e "\t${grayColour}[-e]${endColour}${yellowColour} Exploration Mode${endColour}"
    echo -e "\t\t${purpleColour}all_machines${endColour}${yellowColour}:\t\t\t List all machines${endColour}"
    echo -e "\t\t${purpleColour}active_machines${endColour}${yellowColour}:\t\t List active machines${endColour}"
    echo -e "\t\t${purpleColour}retired_machines${endColour}${yellowColour}:\t\t List retired machines${endColour}"
    echo -e "\t\t${purpleColour}active_linux_machines${endColour}${yellowColour}:\t\t List active Linux machines${endColour}"
    echo -e "\t\t${purpleColour}active_windows_machines${endColour}${yellowColour}:\t List active Windows machines${endColour}"
    echo -e "\t\t${purpleColour}active_freebsd_machines${endColour}${yellowColour}:\t List active FreeBSD machines${endColour}"
    echo -e "\t\t${purpleColour}active_openbsd_machines${endColour}${yellowColour}:\t List active OpenBSD machines${endColour}"
    echo -e "\t\t${purpleColour}active_other_machines${endColour}${yellowColour}:\t\t List active Other machines${endColour}"
    echo -e "\t\t${purpleColour}retired_linux_machines${endColour}${yellowColour}:\t\t List retired Linux machines${endColour}"
    echo -e "\t\t${purpleColour}retired_windows_machines${endColour}${yellowColour}:\t List retired Windows machines${endColour}"
    echo -e "\t\t${purpleColour}retired_freebsd_machines${endColour}${yellowColour}:\t List retired FreeBSD machines${endColour}"
    echo -e "\t\t${purpleColour}retired_openbsd_machines${endColour}${yellowColour}:\t List retired OpenBSD machines${endColour}"
    echo -e "\t\t${purpleColour}retired_other_machines${endColour}${yellowColour}:\t\t List retired Other machines${endColour}\n"
    echo -e "\t${grayColour}[-s]${endColour}${yellowColour} Search by machine name${endColour} ${blueColour}\t(Example: -s Rope)${endColour}\n"
    echo -e "\t${grayColour}[-i]${endColour}${yellowColour} Search by IP Address${endColour} ${blueColour}\t(Example: -i 10.10.10.10)${endColour}\n"
    echo -e "\t${grayColour}[-f]${endColour}${yellowColour} Search username${endColour} ${blueColour}\t\t(Example: -f s4vitar)${endColour}\n"
    tput cnorm; exit 1
}

tput civis; while getopts ":e:t:g:s:i:f:h:" arg; do
	case $arg in
		e) explorer_mode=$OPTARG;;
        t) API_TOKEN=$OPTARG;;
        g) generate_files=$OPTARG;;
		s) search_machine_name=$OPTARG;;
        i) ip_address=$OPTARG;;
        f) user_name=$OPTARG;;
		h) helpPanel;;
	esac
done

if [ "$(echo $generate_files)" == "1" ]; then
    generateFiles
elif [ "$(echo $generate_files)" == "0" ]; then
    if [ ! -f $tmp_file ]; then
        generateFiles
    fi
fi

if [ $search_machine_name ] && [ $API_TOKEN ]; then
	searchMachineName $search_machine_name
	exit 0
fi

if [ $ip_address ] && [ $API_TOKEN ]; then
    searchIPAddress $ip_address
    exit 0
fi

if [ $user_name ] && [ $API_TOKEN ]; then
    searchUserName $user_name
    exit 0
fi

if [ $explorer_mode ] && [ $API_TOKEN ] && [ $generate_files ]; then
    if [ "$(echo $explorer_mode)" == "all_machines" ]; then
        getAllMachines
    elif [ "$(echo $explorer_mode)" == "active_machines" ]; then
        getActiveMachines
    elif [ "$(echo $explorer_mode)" == "retired_machines" ]; then
        getRetiredMachines
    elif [ "$(echo $explorer_mode)" == "active_linux_machines" ]; then
		getActiveLinuxMachines
	elif [ "$(echo $explorer_mode)" == "active_windows_machines" ]; then
		getActiveWindowsMachines
	elif [ "$(echo $explorer_mode)" == "retired_linux_machines" ]; then
		getRetiredLinuxMachines
	elif [ "$(echo $explorer_mode)" == "retired_windows_machines" ]; then
		getRetiredWindowsMachines
    elif [ "$(echo $explorer_mode)" == "active_freebsd_machines" ]; then
        getActiveFreebsdMachines
    elif [ "$(echo $explorer_mode)" == "retired_freebsd_machines" ]; then
        getRetiredFreebsdMachines
    elif [ "$(echo $explorer_mode)" == "retired_openbsd_machines" ]; then
        getRetiredOpenbsdMachines
    elif [ "$(echo $explorer_mode)" == "active_openbsd_machines" ]; then
        getActiveOpenbsdMachines
    elif [ "$(echo $explorer_mode)" == "active_other_machines" ]; then
        getActiveOtherMachines
    elif [ "$(echo $explorer_mode)" == "retired_other_machines" ]; then
        getRetiredOtherMachines
    fi
else
    helpPanel
fi; tput cnorm

